### ISSUE TITLE
"Could not find any reads in example_sample1-ClassII-2nditeration_2.fq"

### ISSUE THREAD

**Issue by NicoleThue** [RENXI-NUS/IPA-neoantigen-prediction#2]
Hello, I'm trying to get the pipeline up and running with the example dataset, but I keep getting this error that are no alignments in the bowtie log. Because of this error it doesn't produce the ClassII-2nditeration_2.fq files and keeps the pipeline from completing. This happens right in the beginning, so it likely has to do with the seq2_HLA scripts, but I'm just not sure where the issue is coming from.

**Comment by ShirAmit96** [comment]
I'm having the same issue Nicole mentioned. If anyone has a solution, please let me know.

**Comment by jeremymchacon** [comment]
I also see this warning with the example data, but I assume it appears because 100% of the reads aligned in the first iteration. However, I do get an error later on (I replaced my actual path with a placeholder). @RENXI-NUS , do you have any thoughts on how to fix this? Thank you!

***** ERROR: Requested column 4, but database file [mypathstuff]/test_output/example.cluster.sorted.bed only has fields 1 - 0.

This seems to come after a problem in ./predict_polyA_spanning_reads.sh; the process running this appears to be killed based upon the log, and I have not figured out the cause just yet. Here's that part of the log, which culminates in the error:

Dec 06 15:03:34 ..... started STAR run
Dec 06 15:03:35 ..... loading genome
./predict_polyA_spanning_reads.sh: line 12: 3205477 Killed                  "$STAR" --genomeDir "$STAR_library" --runThreadN 20 --limitBAMsortRAM 100000000000 --limitIObufferSize 1000000000 1000000000 --readFilesIn "$file1" "$file2" --outSAMtype BAM Unsorted --outFileNamePrefix "$path/$line" --readFilesCommand zcat
Dec 06 15:03:55 ..... started STAR run
Dec 06 15:03:56 ..... loading genome
./predict_polyA_spanning_reads.sh: line 12: 3205568 Killed                  "$STAR" --genomeDir "$STAR_library" --runThreadN 20 --limitBAMsortRAM 100000000000 --limitIObufferSize 1000000000 1000000000 --readFilesIn "$file1" "$file2" --outSAMtype BAM Unsorted --outFileNamePrefix "$path/$line" --readFilesCommand zcat
mkdir: cannot create directory '/[mypathstuff]/test_output’: File exists
mkdir: cannot create directory ‘/[mypathstuff]/test_output/logs’: File exists
grep: [mypathstuff]/test_output/example_sample1*Log.final.out: No such file or directory
2022-12-06 15:04:27 Call cluster based on extracted soft clipped reads!
there are totally 0 reads in all loci
there are totally 0 reads in single loci
there are totally 0 reads in the cluster
grep: [mypathstuff]/test_output/example_sample2*Log.final.out: No such file or directory
2022-12-06 15:04:27 Call cluster based on extracted soft clipped reads!
there are totally 0 reads in all loci
there are totally 0 reads in single loci
there are totally 0 reads in the cluster
2022-12-06 15:04:27 Find peaks for polyA clusters of all samples!

*****
***** ERROR: Requested column 4, but database file [mypathstuff]/test_output/example.cluster.sorted.bed only has fields 1 - 0.

**Comment by RENXI-NUS** [comment]
Sorry for the late reply. I rerun the seq2_HLA script and cannot reproduce your error. Did you use python 2 to call the seq2HLA scripts? Also you need to install biopython for running seq2HLA script using something like "conda install biopython". If still cannot work, can you try your own paired end RNAseq dataset to see if you still observe the error. Thanks.

**Comment by jeremymchacon** [comment]
Hi @RENXI-NUS, cool pipeline! I also get the same warning as @NicoleThue, although I assumed that the example data simply didn't have any class 2 HLA reads. This is what the top part of my log looks like:  

`rename: not enough arguments

Usage:
 rename [options] expression replacement file...

Options:
 -v, --verbose    explain what is being done
 -s, --symlink    act on symlink target

 -h, --help     display this help and exit
 -V, --version  output version information and exit

For more details see rename(1).
# reads processed: 1677
# reads with at least one reported alignment: 1677 (100.00%)
# reads that failed to align: 0 (0.00%)
Reported 119961 paired-end alignments to 1 output stream(s)
Warning: Could not find any reads in "/home/riss/chaco001/pasram/test_output/example/example_sample1/example_sample1-ClassII-2nditeration_1.fq"
Warning: Could not find any reads in "/home/riss/chaco001/pasram/test_output/example/example_sample1/example_sample1-ClassII-2nditeration_2.fq"
# reads processed: 0
# reads with at least one reported alignment: 0 (0.00%)
# reads that failed to align: 0 (0.00%)
No alignments
Now running seq2HLA version 2.2.!
Input is a gipped file .....
The read length of your input fastq was determined to be 48, so 1 mismatches will be allowed and 12 threads will be used by bowtie.
----------HLA class I------------
First iteration starts....
Mapping ......
# reads processed: 114736
# reads with at least one reported alignment: 5131 (4.47%)
# reads that failed to align: 109605 (95.53%)
Reported 420338 paired-end alignments to 1 output stream(s)

Calculation of first digital haplotype.....
The digital haplotype is written into /home/riss/chaco001/pasram/test_output/example/example_sample1/example_sample1-ClassI.digitalhaplotype1
1st iteration done.
Now removing reads that mapped to the three top-scoring groups .......
Second iterations starts .....
 Mapping ......
Calculation of second digital haplotype.....
The digital haplotype is written into /home/riss/chaco001/pasram/test_output/example/example_sample1/example_sample1-ClassI.digitalhaplotype2
2nd iteration done.
-----------2 digit typing results-------------
#Locus	Allele 1	Confidence	Allele 2	Confidence
A	A*02	1.914287e-05	A*11	0.001489945
B	B*67	0.1258518	B*15	0.004450812
C	C*07	0.01216089	C*08	0.02312405
Calculation of locus-specific expression ...
/home/riss/chaco001/pasram/test_output/example/example_sample1/example_sample1-ClassI.bowtielog
A: 15867.78 RPKM
C: 25236.48 RPKM
B: 2273.1 RPKM
-----------4 digit typing results-------------
#Locus	Allele 1	Confidence	Allele 2	Confidence
!A	A*02:03'	1.914287e-05	A*11:02'	0.001489945
!B	B*67:02	0.1258518	B*15:25'	0.004450812
!C	C*07:02	0.01299892	C*08:01	0.02312405
----------HLA class II------------
ClassII: first iteration starts....
Mapping ......
# reads processed: 114736
# reads with at least one reported alignment: 0 (0.00%)
# reads that failed to align: 114736 (100.00%)
No alignments

ClassII: calculation of first digital haplotype.....
The digital haplotype is written into /home/riss/chaco001/pasram/test_output/example/example_sample1/example_sample1-ClassII.digitalhaplotype1
1st iteration done.
Now removing reads that mapped to the three top-scoring groups .......
Nothing to remove
`

Note that it finds and aligns class I HLA reads, but not class II. Note also the failed rename at the top, which I assume/hope is not critical?

Would it be possible to include the log file that you get when you run the example data? That would help me troubleshoot some other issues I have been having. Thanks!

**Comment by RENXI-NUS** [comment]
Hello! Sure. I attach the log file here for your reference.
[log.txt](https://github.com/RENXI-NUS/IPA-neoantigen-prediction/files/12065884/log.txt)
